### ISSUE TITLE
after change in db retrun changed value

### ISSUE THREAD

**Issue by vahidalvandi** [renoki-co/laravel-eloquent-query-cache#105]
hi

after use     use QueryCacheable;   i want to automaticlly add cache in model like  page::find(1); 
must add cacheFor(60 * 60) in each model ?

**Comment by rennokki** [comment]
You just have to add `$cacheFor` in your model, and all queries will be cached by default.

```php
class Post extends Model
{
   /**
     * Specify the amount of time to cache queries.
     * Do not specify or set it to null to disable caching.
     *
     * @var int|\DateTime
     */
    public $cacheFor = 3600;

     // ...
}
```

**Comment by vahidalvandi** [comment]
also need to    protected static $flushCacheOnUpdate = true;  ?

```
    use QueryCacheable;

    protected static $flushCacheOnUpdate = true;
    public $cacheFor = 3600; // cache time, in seconds
```

**Comment by rennokki** [comment]
Only if you want the package to auto-flush the cache for you when records get added/deleted/updated.
