### ISSUE TITLE
PHPStorm complains about method signature

### ISSUE THREAD

**Issue by denisgoryaynov** [renoki-co/laravel-eloquent-query-cache#113]
When using cacheTags or cacheFor directly on a model query instance, for example ```Organization::cacheTags(['tag1', 'tag2'])->get()```, PHPStorm complains that 'Method call is provided 1 parameters, but the method signature uses 0 parameters' because of the doc block portion in [src/Traits/QueryCacheable.php](https://github.com/renoki-co/laravel-eloquent-query-cache/blob/178897edbdcc7391281db2fce7665ff74c2931c5/src/Traits/QueryCacheable.php#L8). Currently the methods are declared like this:
```
... other methods ...
 * @method static \Illuminate\Database\Query\Builder|static cacheFor()
 * @method static \Illuminate\Database\Query\Builder|static cacheTags()
... other methods ...
```

Adding the method signature to the doc block portion fixes the issue:
```
... other methods ...
 * @method static \Illuminate\Database\Query\Builder|static cacheFor(\DateTime|int|null  $time)
 * @method static \Illuminate\Database\Query\Builder|static cacheTags(array $cacheTags = [])
... other methods ...
```
But I don't know if it's the best way to solve this because it requires to copy methods signatures from src/Traits/QueryCacheModule.php every time.

**Comment by rennokki** [comment]
Thanks for mentioning! :D

Fixed in https://github.com/renoki-co/laravel-eloquent-query-cache/commit/12669e1019f5da48d4f765702abf7a66f2e4bbba.
