### ISSUE TITLE
[improvement] Updating `BelongsToMany` relationship doesn't flush the cache

### ISSUE THREAD

**Issue by duncanmcclean** [renoki-co/laravel-eloquent-query-cache#135]
### Brief description

We're running into an issue with this package - when our client goes to add/delete something on a `BelongsToMany` relation on the Product model, the list reloads but there's no change. I also see the same list in our site's frontend but the database is updated correctly.

### Implementation

We're using this package on our `Product` model, relevant code below:

```php
// app/Models/Product.php

use Chelout\RelationshipEvents\Concerns\HasBelongsToEvents;
use Chelout\RelationshipEvents\Concerns\HasBelongsToManyEvents;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Rennokki\QueryCache\Traits\QueryCacheable;

class Product extends Model
{
    use HasFactory;
    use HasBelongsToEvents;
    use HasBelongsToManyEvents;
    use QueryCacheable;

    protected $guarded = [];

    /**
     * Invalidate the cache automatically
     * upon update in the database.
     *
     * @var bool
     */
    protected static $flushCacheOnUpdate = true;

    /**
     * Specify the amount of time to cache queries.
     * Do not specify or set it to null to disable caching.
     *
     * @var int|\DateTime
     */
    public $cacheFor = 86400;

    // ...
}
```

On this product model, we have a `belongsToMany` relationship called `bedTypes`:

```php
public function bedTypes()
{
    return $this->belongsToMany(BedType::class);
}
```

---

I'm aware the `BelongsToMany` events aren't handled by this package - would you prefer if I post an issue on the [laravel-relationship-events](https://github.com/chelout/laravel-relationship-events) package instead?

**Comment by rennokki** [comment]
Use the Cache Tags feature to set and invalidate specific queries based on assigned Redis/Memcached tags.
