### ISSUE TITLE
Don't use cache depends on config

### ISSUE THREAD

**Issue by quevlu** [renoki-co/laravel-eloquent-query-cache#136]
Hi, thanks for your time for this great package. I've been searching for closed issues and PRS, but I didn't find any related to what I want to do. Is there any possibility to prevent the use of cache with a config file?

**Comment by rennokki** [comment]
You can cache queries individually if this is what you want: https://leqc.renoki.org/cache-tags/query-caching#enable-disable-caching-on-demand

**Comment by rennokki** [comment]
I get the point, but why would you want to enable/disable the cache at the config level (per entire app)?

**Comment by quevlu** [comment]
I've had some problems with test cases

**Comment by rennokki** [comment]
You might want to delete the entire cache before each test using the PHPunit's `setUp()` method? Or within the tests?

**Comment by Endy-c** [comment]
You can use these code in each of your models to implement your requirement:
``` php
if (config('your.config.usecache')) {
    use QueryCacheable;
}
```
