### ISSUE TITLE
have question in relation

### ISSUE THREAD

**Issue by vahidalvandi** [renoki-co/laravel-eloquent-query-cache#143]
hi . i have two model  and have QueryCacheable trait in both aslo have HasOne relation like bellow

```
$item->product->quantity
$item->product->amount
```
Will this relationship be cached? ?

**Comment by vahidalvandi** [comment]
> See: https://leqc.renoki.org/cache-tags/relationships-caching

please simple say (yes or no )

i dont understand top link

**Comment by rennokki** [comment]
They won't be cached unless you use the function to cache.

**Comment by vahidalvandi** [comment]
thank you . how i can function cache in view ?

for example i have book and need get auther book  , in view i get book and call auther like bellow
`$book->auther->name;`
