### ISSUE TITLE
Not compatible with ```Model::preventAccessingMissingAttributes()```

### ISSUE THREAD

**Issue by maciek-szn** [renoki-co/laravel-eloquent-query-cache#163]
Laravel 9.35 introduced ```Model::preventAccessingMissingAttributes()``` option (laravel/framework#44283). However this package isn't quite compatible with this mechanism, as it sometimes returns an error: ```The attribute [cacheTags] either does not exist or was not retrieved for model...```

**Comment by rennokki** [comment]
I have opened https://github.com/renoki-co/laravel-eloquent-query-cache/pull/165, but it seems like the tests locally pass, even when I test for both `false/true` for strict mode.

Do you have any snippet from which the problem comes off?

**Comment by maciek-szn** [comment]
I'll try to provide more information tomorrow. There might be Laravel Livewire involved.

**Comment by maciek-szn** [comment]
It seems to me that there is a problem with passing a whole model to a Livewire component (see: [Passing parameters](https://laravel-livewire.com/docs/2.x/rendering-components#parameters)). However the error isn't invoked on the first rendering of a Livewire component, only after refreshing it.

Should I open an issue in the [Livewire](https://github.com/livewire/livewire) repository? To be honest, I don't quite know what's going on under the hood and how the two libraries work together.

**Comment by rennokki** [comment]
@maciek-szn I can test against livewire. Do you have any mockup component i can start from?

**Comment by maciek-szn** [comment]
I've created a [test repository](https://github.com/maciek-szn/query-cache-test).

**Comment by rennokki** [comment]
@maciek-szn I was able to fix it.

**Comment by maciek-szn** [comment]
Thanks a lot!
