### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by maciek-szn** [renoki-co/laravel-eloquent-query-cache#174]
Looks like [Laravel 10 will be released in one week](https://laravel.com/docs/9.x/releases#support-policy). Are there any chances for update? Thanks! 🙏

**Comment by szhorvath** [comment]
Yes, please.

**Comment by tomasbreffitt** [comment]
Was looking into opening a PR, looks like it is dependant on https://github.com/chelout/laravel-relationship-events/pull/56

**Comment by advil0** [comment]
> Was looking into opening a PR, looks like it is dependant on [chelout/laravel-relationship-events#56](https://github.com/chelout/laravel-relationship-events/pull/56)

Looks like they just released Laravel 10 support!  https://github.com/chelout/laravel-relationship-events/releases/tag/v2.0.0

**Comment by advil0** [comment]
Looks like it is also dependent on https://github.com/orchestral/database, which says "READ-ONLY", anyone got any ideas?

**Comment by tomasbreffitt** [comment]
@advil0 I was looking into this, I'm confident that the only orchestral repo needed is testbench, so database and testbench-core can be removed.

I'll have a chance to look at opening a PR in the AM PST

**Comment by advil0** [comment]
> @advil0 I was looking into this, I'm confident that the only orchestral repo needed is testbench, so database and testbench-core can be removed.
> 
> I'll have a chance to look at opening a PR in the AM PST, but feel free to beat me to it. Should just require updating dependancies, I believe I did that and tests passed.

Oh neat!  I just submitted the PR, it's possible I didn't get something right so feel free to add a comment/etc if something else just needs to be changed.

**Comment by gunner1095** [comment]
Hi all, any word on when Laravel 10 will be supported?

**Comment by advil0** [comment]
> Hi all, any word on when Laravel 10 will be supported?

I haven't heard anything but it looks like the maintainer of the repo updated my PR a day or so ago, so hopefully soon!

**Comment by vadson777** [comment]
Any progress?

**Comment by Henriquex25** [comment]
@rennokki Any progress ?

**Comment by mstfbysl** [comment]
@rennokki ? We are looking for it

**Comment by Wernke96** [comment]
It released.
