### ISSUE TITLE
DontCache doesn't apply to a relation

### ISSUE THREAD

**Issue by milosb793** [renoki-co/laravel-eloquent-query-cache#194]
When using `Model::dontCache()` method, seems like it doesn't apply to relations. Model don't cache, but relations does. Here's an example:

```
User::noCache()
  ->with(['team'])
  ->where('email', 'user@example.com')
  ->first();
```

In this case, a user will not be cached, but a team will. 

Is there any workaround for this?

**Comment by rennokki** [comment]
@milosb793 The relationships is not inheriting any cache settings from the main query.

**Comment by milosb793** [comment]
Just a heads-up if anyone else is having such issues, it's `dontCache()` instead of `noCache()`:

```
User::noCache()
  ->with(['team' => fn ($q) => $q->dontCache()])
  ->with(['team'])
  ->where('email', 'user@example.com')
  ->first();
```
