### ISSUE TITLE
Version 1.4.0 requires only cache drivers that support tags

### ISSUE THREAD

**Issue by teodoriu** [renoki-co/laravel-eloquent-query-cache#21]
Hi,

I updated to the latest version (1.4.0) and it looks that it doesn't support the file cache driver anymore.

It is working fine on 1.3.1, and for what i need it's enough.

Can you keep the functionality in later versions too?

**Comment by rennokki** [comment]
Have you tried to set the global tags array to empty array like described here: file:///android_asset/md/#global-cache-invalidation ?

**Comment by rennokki** [comment]
Have you tried setting `getCacheBaseTags` function to empty array within your model like described in the docs?

**Comment by rennokki** [comment]
I'll close this issue until further feedback is given.
