### ISSUE TITLE
Support for Laravel 11.x

### ISSUE THREAD

**Issue by faizananwerali** [renoki-co/laravel-eloquent-query-cache#216]
Any idea when Laravel 11.x will be supported?

**Comment by iamacarpet** [comment]
Blocker for me, as we're using this as a dependency on an Eloquent driver for Google's Cloud Datastore:

https://github.com/affordablemobiles/eloquent-datastore

@rennokki would you be responsive to a PR, if it helps to unblock things?

**Comment by lloricode** [comment]
+1

**Comment by lloricode** [comment]
see https://github.com/renoki-co/laravel-eloquent-query-cache/pull/219

**Comment by lloricode** [comment]
this package mention here https://laracasts.com/series/small-laravel-packages-big-impact/episodes/12

**Comment by rennokki** [comment]
Merged #219. Will follow tag.
