### ISSUE TITLE
global cache invalidation

### ISSUE THREAD

**Issue by MoZayani97** [renoki-co/laravel-eloquent-query-cache#24]
I needed to clear cache on logout so I imported the trait in my controller and did this

```
public function logout() {
            admins::flushQueryCache();
            invitations::flushQueryCache();
            customers::flushQueryCache();
            rides::flushQueryCache();
            users::flushQueryCache();
}
```

am I doing something wrong?

**Comment by rennokki** [comment]
The trait should be used within the model, not the controller.

**Comment by MoZayani97** [comment]
soo how can I invalidate it on logout ?

**Comment by rennokki** [comment]
Each of the `admin`, `invitations`, etc. models should use the trait as described in the documentation.
