### ISSUE TITLE
inner join statements not cached !

### ISSUE THREAD

**Issue by jehadja** [renoki-co/laravel-eloquent-query-cache#26]
Hi, and thanks for the great works!
I have an issue with inner join statements are not cached example:
**while mostly think the issue because the pluck method not added to model methods!**

`select "discount" from "products" inner join "category_product" on "products"."id" = "category_product"."product_id" where "category_product"."category_id" = 29 and "active" = 1 and exists (select * from "categories" where "products"."category_id" = "categories"."id") order by "category_product"."order" asc`

while Products Model are cached, category_product model cached and categories model cached!
statement example 

```
  $Products =  new  \App\Category ;
            $Products = $Products->newQuery();
            $Products = $Products->find($cat->id)->ProductsN()->has("Mcat")->with('Mcat');
            $DiscountIds =  $Products->pluck("discount")->toArray();
```
any ideas ?

thanks in advance

**Comment by rennokki** [comment]
The `pluck` method is just a shorthand for `->get()->pluck()`, so this is not the issue here.

Please see how to cache relationships in the `->with()` method: https://github.com/renoki-co/laravel-eloquent-query-cache#relationship-caching

**Comment by rennokki** [comment]
About the `$Products` query, make sure you attached the trait to the model that is called in the `ProductsN()` method.

**Comment by jehadja** [comment]
Thanks for fast responde 

```
    public function ProductsN()
    {
        return   $this->belongsToMany('App\Product', 'category_product')->Active();
    }
```
all model product and category + category_product model has the following 
```
use Rennokki\QueryCache\Traits\QueryCacheable;
class [name of model] extends Model
{
    use QueryCacheable;
    public $cacheFor = 60*24*7; // 7 days
    protected static $flushCacheOnUpdate = true;
}
```

**Comment by rennokki** [comment]
Both models should have the trait implemented.

**Comment by jehadja** [comment]
Hi, it has as I wrote previously!
the issue according to my understanding 
`$this->belongsToMany('App\Product', 'category_product')->Active();`

**Comment by rennokki** [comment]
Are you able to call `$Products->find($cat->id)->ProductsN()->cacheFor(60)` ?
