### ISSUE TITLE
Some query not caching.

### ISSUE THREAD

**Issue by sindhu13** [renoki-co/laravel-eloquent-query-cache#28]
Some query not caching...
```
use Rennokki\QueryCache\Traits\QueryCacheable;
class Event extends Model {
    use QueryCacheable;

    protected $cacheFor = 60 * 60; // 1 hour

    protected static $flushCacheOnUpdate = true;

    /**
     * Set the base cache tags that will be present
     * on all queries.
     *
     * @return array
     */
    protected function getCacheBaseTags(): array
    {
        return [
            'event_tag',
        ];
    }
}
```
i put this on every models, with different tag each model...

but some query is not caching why..?.
and how i can check is that my query is caching..?.,
if not caching how i can check, why thats query is not cache...

thankyou...
sorry for my english...

**Comment by rennokki** [comment]
Check this, under the section `Log Query in Laravel`: https://artisansweb.net/how-to-log-query-in-laravel/

You can set up a listener in the `boot` method of your `AppServiceProvider` with something like this:

```php
DB::listen(function($sql) {
    Log::info($sql->sql);
    Log::info($sql->bindings);
    Log::info($sql->time);
});
```

And eventually checking your `storage/logs/laravel.log` file for what the app logged.
Triggering the queries multiple times should return only one log line.

**Comment by sindhu13** [comment]
Log query is ok...
but my query still not cache...
here from debugbar...
![querycache](https://user-images.githubusercontent.com/2950240/81787265-f7fdec80-952a-11ea-88e7-0212e1d19d69.jpg)
every time i refresh the page...
still like that...
any suggest..?.

**Comment by rennokki** [comment]
Will it work if you set up the `$cacheFor` as public instead of protected?

**Comment by sindhu13** [comment]
not working...
the query still not cache...

**Comment by sindhu13** [comment]
i know...
the query actually is cached...
because i use DateTime, every query is different by the seconds...

sorry...
my bad...
i don't realize it... :)
