### ISSUE TITLE
Bug with tags on cache driver 'file' 

### ISSUE THREAD

**Issue by mirkojvc** [renoki-co/laravel-eloquent-query-cache#29]
<img width="613" alt="Screenshot 2020-05-21 at 13 30 53" src="https://user-images.githubusercontent.com/18366380/82555029-4df41500-9b67-11ea-8a8e-7f1eb6585686.png">
The problem is with the return in QueryCacheable->newBaseQueryBuilder(), it returns 

        `return $builder->cacheBaseTags($this->getCacheBaseTags());`

It should have a base tags check like: 

        // changed so it could work without base tags
        if ($this->cacheBaseTags) {
            $builder
           ->cacheBaseTags($this->getCacheBaseTags());
         }
         return $builder;

**Comment by rennokki** [comment]
You can bypass the errors by overwriting the `getCacheBaseTags()` method in your model:

```php
protected function getCacheBaseTags(): array
{
    return [
        //
    ];
}
```

**Comment by mrbenosborne** [comment]
> You can bypass the errors by overwriting the `getCacheBaseTags()` method in your model:
> 
> ```
> protected function getCacheBaseTags(): array
> {
>     return [
>         //
>     ];
> }
> ```

Not sure bypassing the errors is the correct thing here?

Can check as per @mirkojvc suggestion to check if cacheBaseTags exist?

**Comment by rennokki** [comment]
What i actually meant was that each model has by default the base tags set as the model name, so overwriting them should fix the issue since there will be no more tags and the package will respect this and not use the tags.

**Comment by rennokki** [comment]
If no base cache tags are set, the overall cache functionality will not trigger the `tag()` method:

https://github.com/renoki-co/laravel-eloquent-query-cache/blob/master/src/Traits/QueryCacheModule.php#L332-L337

**Comment by hertz1** [comment]
Sorry for reviving this topic, but I'm considering using this package for a project and came across this issue while avaliating the viability of it on my machine. The thing is: we use different cache drivers per enviroment, `file` in development and `redis` in production.

As per @rennokki's suggestion, if we overwrite the `getCacheBaseTags()` method in the model, we lose the tag funcionality in all drivers, even on those who support tagging.

I'm not sure what the best solution is here, but I think users should be able to change cache drivers without changing their code.

**Comment by rennokki** [comment]
@hertz1 Indeed, I will think about working this out for some better behavior. Until then, I can only think of one solution: try to set dev to use a driver that supports tagging, like Redis or Memcached.

Laravel Homestead would set up a test instance, with Virtualbox that has Redis/Memcached, with ease: https://laravel.com/docs/7.x/homestead

**Comment by rennokki** [comment]
https://github.com/renoki-co/laravel-eloquent-query-cache/pull/37

Tagged https://github.com/renoki-co/laravel-eloquent-query-cache/releases/tag/2.2.0
