### ISSUE TITLE
Not supporting raw DB queries

### ISSUE THREAD

**Issue by EgoistDeveloper** [renoki-co/laravel-eloquent-query-cache#30]
I have some complex queries and have to use **[DB](https://laravel.com/docs/7.x/queries#joins)** class but package it seem to not supported. Is is possible?

**Comment by hmrneves1** [comment]
Hi @EgoistDeveloper, at the moment seems that the package only supports Models.

**Comment by rennokki** [comment]
Hello @EgoistDeveloper, the thing is that the DB class actively binds to a DB connection from `config/database.php`, so for the whole process to crank up and make use of it, either it should be a new DB facade created, either a new connection created and configured.

Either way, Laravel **Eloquent** Query Cache is straight-forward and willing to keep the features at the Eloquent-level.
