### ISSUE TITLE
Suggest: Delete cache with Wildcard 

### ISSUE THREAD

**Issue by reksmeysrey** [renoki-co/laravel-eloquent-query-cache#31]
Caching
$model->cacheTags(['Tags.id.name'])

Delete cache like this:
$model->flushQueryCache(['Tags.*'])

Or like : 
$model->tags('Tags')->flush()

**Comment by rennokki** [comment]
The package uses the underlying `Cache` facade of `laravel/framework`. Wildcard tag caching should be addressed to [laravel/framework](https://github.com/laravel/framework).

I am not really sure if Redis supports wildcard tagging caching and flushing.
