### ISSUE TITLE
cache queries to specific table

### ISSUE THREAD

**Issue by omidMolaverdi** [renoki-co/laravel-eloquent-query-cache#34]
Hi,

As expected I am not a technical person. The purpose that I am chasing is to cache all queries in the form of DB::(TABLE)->where('XXX','YYY')->get()->toArray() or similarly DB::(TABLE)->whereRaw('XXX','YYY')->get()->toArray(). The cache should invalidate on update/create/delete. Please can you kindly guide on steps?

**Comment by rennokki** [comment]
This issue is somehow similar to https://github.com/renoki-co/laravel-eloquent-query-cache/issues/30

`DB` is not supported. As the package name implies, it caches only queries within models.

**Comment by omidMolaverdi** [comment]
Thanks a lot for the reply and details.
