### ISSUE TITLE
cache for individual users

### ISSUE THREAD

**Issue by omidMolaverdi** [renoki-co/laravel-eloquent-query-cache#35]
I have a table in the database that assigned a model to. This table has a user_id and I want to cache the queries for the user individually. In other words, I need users to have their own specific cache so that I do not remove a global cache when invalidate. I did a prefix `->cachePrefix('m'.$user_id.'_')` but do not know how to invalidate on update/insert/delete. Please can you help?

**Comment by rennokki** [comment]
Prefixes are in case you have multiple applications on the same cache driver.

I assume you might want to use caching tags. You can have something like this in your controller, for example:

```php
public function index(Request $request)
{
    $user = $request->user();

    $posts = $user->posts()->cacheTags(["user:{$user->id}"])->get();

    return response()->json($posts);
}
```

To invalidate it, just run:

```php
User::flushQueryCache(["user:{$user->id}"]);
```
