### ISSUE TITLE
flushQueryCache method not found

### ISSUE THREAD

**Issue by RJFares** [renoki-co/laravel-eloquent-query-cache#40]
I have an Account model, and it implements Rennokki\QueryCache\Traits\QueryCacheable.
Current version 2.4.2

I am calling `Account::flushQueryCache(); ` to flush the cache.

My IDE mentions the method is not found, and the cache is not being cleared in tests. I did not find the method in QueryCacheable either.
What am I missing :)

**Comment by rennokki** [comment]
The function exists: https://github.com/renoki-co/laravel-eloquent-query-cache/blob/master/src/Traits/QueryCacheModule.php#L167

It depends on how you use the function and if using tags with it or not.

**Comment by RJFares** [comment]
As a test, I wrote:
`dump(json_encode(Account::flushQueryCache()));`
It's returning empty, no true nor false.

The model:
```
class Account extends Model
{
    use QueryCacheable;

    protected static $flushCacheOnUpdate = true;

    public $cacheFor = 1;

[...]
}
```

**Comment by rennokki** [comment]
`flushQueryCache` is a void function, it doesn't return anything. The cache does get invalidated. Having `$cacheFor` to `1` is going to cache everything for 1 second.

**Comment by RJFares** [comment]
I figured out the problem. I'm using Livewire, and the command to flush and the rendering take place too quickly, maybe faster than the time it takes for the cache to clear. 
Instead of having to manually refresh every time to see the updated results, I added sleep(1) after the Account::flushQueryCache() and it worked.
Not sure if there is a better way you can think of for people using Livewire?

**Comment by RJFares** [comment]
Is flushQueryCache tested on "file" caching? 

```
$user->forceFill([
    'current_team_id' => $team->id,
])->save();

User::flushQueryCache();
dump('After flush',User::findOrFail(auth()->id()));
dump('No cache', User::dontCache()->findOrFail(auth()->id()));
```
The result of dump 1 is different than dump 2! Only dontCache result is up to date. Not sure what to share since I just implemented as docs described.
