### ISSUE TITLE
Caching is not working for 'loadCount'

### ISSUE THREAD

**Issue by iamroi** [renoki-co/laravel-eloquent-query-cache#42]
Thanks for the great package!

I have trouble with Laravel's loadCount method. Could you please give your advice for a workaround?

```
$user->loadCount(['phones' => function ($query) {
    return $query->cacheFor(now()->addMonths(3));
}]);
```

Query is

```
select `id`, (select count(*) from `phones` where `users`.`id` = `phones`.`user_id`) as `phones_count` 
from `users` where `users`.`id` in ('1');
```

**Comment by rennokki** [comment]
The model that governs the `phones` model should implement the query cache functionalities too.

**Comment by iamroi** [comment]
@rennokki I can confirm both models are using the trait `QueryCacheable` so I'm not sure what I'm missing here.

**Comment by rennokki** [comment]
It then means it caches it properly.
