### ISSUE TITLE
BadMethodCallException getDb()

### ISSUE THREAD

**Issue by lucabecchetti** [renoki-co/laravel-eloquent-query-cache#47]
In Laravel 7, i have this:

Call to undefined method Rennokki\QueryCache\Query\Builder::getDb() 

 Bad Method Call

Did you mean Rennokki\QueryCache\Query\Builder::get() ?

**Comment by rennokki** [comment]
This is not coming from the package since we do not use `getDb()` anywhere. You might want to look after this method call within your code.
