### ISSUE TITLE
Trait method newBaseQueryBuilder, collisions with other trait method

### ISSUE THREAD

**Issue by miharbi** [renoki-co/laravel-eloquent-query-cache#49]
`Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods on App\\`

I'm using https://github.com/grimzy/laravel-mysql-spatial and it has the other newBaseQueryBuilder, I'm trying some of this https://github.com/renoki-co/laravel-eloquent-query-cache#advanced but I'm not getting good results, could some one give some advice or example?

**Comment by rennokki** [comment]
Unfortunately, editing the default builder is the only way to make this package work.
