### ISSUE TITLE
Does this work with *Eloquent* builder...?

### ISSUE THREAD

**Issue by telkins** [renoki-co/laravel-eloquent-query-cache#50]
This looks like a great package...something I can benefit from.  However, I'm trying to use it with a model where I have my own custom *Eloquent* builder.

Please look at the following link: https://timacdonald.me/dedicated-eloquent-model-query-builders/

The builder extends `Illuminate\Database\Eloquent\Builder` rather than `Illuminate\Database\Query\Builder`.

Am I doing something wrong, or does this not support `Illuminate\Database\Eloquent\Builder`...?

Thanks...!  🤓

**Comment by telkins** [comment]
Nevermind.  It was me.  It is probably working fine.  My focus is on some code that uses `sum()` and `exists()`.  I'll try to extend it and see what happens....

**Comment by rennokki** [comment]
It's not an implementation issue, but rather a workaround to the builder instance. Having a macro perhaps will remove the idea of having an extended builder. 🤔
