### ISSUE TITLE
Laravel 8 Support?

### ISSUE THREAD

**Issue by dennisvandenende** [renoki-co/laravel-eloquent-query-cache#51]
Its a really nice package. Will you support Laravel 8 soon?

**Comment by faustbrian** [comment]
What's not working? It already can be installed with Laravel 8 https://github.com/renoki-co/laravel-eloquent-query-cache/blob/master/composer.json#L16-L17

**Comment by rennokki** [comment]
Make sure you upgrade the package to `^2.5.1` since it fixes a Laravel 8.x security issue.
