### ISSUE TITLE
[ Suggestion ] Flush Many-to-Many Relationships Table 

### ISSUE THREAD

**Issue by hmrneves1** [renoki-co/laravel-eloquent-query-cache#53]
Hello,

I was testing the package and everything works absolutely fine when caching models.

For example if I have a Model with a many-to-many relation, and I update that relation, the cache won't flush and update, even if I use `protected static $flushCacheOnUpdate = true;`.

I was thinking that those relation could have a separated model and define `protected static $flushCacheOnUpdate = true;` there, but IMO isn't really dinamic. 

I don't have the skills to build this feature so, I will leave here the suggestion. Don't really know if it's easy to have an array of relation to flush cache on `attach`, `detach`, `sync` or simply like `protected static $flushRelationsCacheOnUpdate = true;`

### STEPS TO REPRODUCE
1. have a model like Template
2. have a model like Site
3. have a table for a many-to-many relationship between the models
4. on model Template and Site, configure the caching with `public $cacheFor = 86400;` and `protected static $flushCacheOnUpdate = true;`
5. on a basic controller query the Template for id 1 (eg.)
6. after that do `$template->sites()->attach(1)`
7. after, remove attach and reload the page
8. query again the Template::find(1) and `dd($template)`'
9. You should see the relation came empty

Stay safe!

Thanks,
Helder

**Comment by rennokki** [comment]
Have you tried to apply caching traits on [pivot table models](https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models)?

**Comment by hmrneves1** [comment]
Hello, yes I tried. 
[models.zip](https://github.com/renoki-co/laravel-eloquent-query-cache/files/5874994/models.zip)

I attached my models to be more precise.

**Comment by RoccoHoward** [comment]
I came across this package https://github.com/chelout/laravel-relationship-events that adds events to relationships.
It may help to understand what may need to be done to be able to cache the relationship better/flush when it changes.

At the moment, when I add/change a relationship, I just flush the related model which fixes.

Not ideal - especially flushing the whole model. But just need to get around this bug for now.

**Comment by middleftw** [comment]
A quick and dirty way of achieving this would be to create a model for the pivot table but instead of extending Model(Illuminate\Database\Eloquent\Model) you extend from Pivot (Illuminate\Database\Eloquent\Relations\Pivot).This will give you access to listening to model lifecycle events.You can also declare the $dispatchesEvents property on the pivot model (while extending from Model) and pass the required events like so: 

```
protected $dispatchesEvents = [
        'saved' => UserSaved::class,
        'deleted' => UserDeleted::class,
];
```

For simplicity's sake I opted for the first method.

//web.php
```
Route::get("/", function () {
    $categories = \App\Models\Category::where("id", 5)->with(["products" => function($q){
        $q->cacheTags(["category-product-pivot:id:" . 5]);
    }])->first();

    return view("welcome", [
        "categories" => $categories->products->count()
    ]);
});
```

//category_product.php
```
public static function boot()
{
        parent::boot();

        static::deleting(function (category_product $pivot) {
            \App\Models\Product::flushQueryCache(['category-product-pivot:id:' . $pivot->product_id ]);
        });
}
```

//Category.php
```
public function products(){
        return $this->belongsToMany('App\Models\Product')->using('App\Models\category_product');
}
```

**Comment by rennokki** [comment]
@RoccoHoward I might think to implement this 🪐

**Comment by rennokki** [comment]
From what I checked out, the best choice would be to use the [Observer](https://github.com/chelout/laravel-relationship-events#observers) implementation by defining the methods to Query Cache's [internal observer](https://github.com/renoki-co/laravel-eloquent-query-cache/blob/master/src/FlushQueryCacheObserver.php) and eventually the whole setup would be to add the `QueryCacheable` trait and the [appropriate concern from chelout's package](https://github.com/chelout/laravel-relationship-events#available-traits) to the pivot model. The rest should work the same. Now I'm taking action to make the docs and push the implementation. 😁

**Comment by rennokki** [comment]
Ignore the whole idea with the observer. I have written some soon to be default docs: https://leqc.renoki.org/v/3.x/cache-tags/cache-invalidation/many-to-many-automatic-cache-invalidation
