### ISSUE TITLE
Not caching when pluck is used without using get first

### ISSUE THREAD

**Issue by artjomzab** [renoki-co/laravel-eloquent-query-cache#64]
Hello,

thank you for this wonderful project :). Something I noticed:

    Category::whereName('Foobar')->firstOrFail()->values()->get()->pluck('name', 'id')->all();

Cached. get() retrieves all values first. Then specific columns are retrieved.

    Category::whereName('Foobar')->firstOrFail()->values()->pluck('name', 'id')->all();

Not cached. A query is constructed such that not all columns are returned but only those that are specified in pluck.

I would expect the second (better) query to be cached. Is this a limitation of this project?

**Comment by rennokki** [comment]
Let's break it down step by step:

```
Category::whereName('Foobar')
->firstOrFail() -------- this specific value gets cached
->values()
->pluck('name', 'id')
->all();
```

To pluck specific fields, use the columns:

```php
Category::whereName('Foobar')->firstOrFail(['name', 'id']);
```
