### ISSUE TITLE
[feature] jenssegers/laravel-mongodb support

### ISSUE THREAD

**Issue by GregoryWullimann** [renoki-co/laravel-eloquent-query-cache#65]
I'm using https://github.com/jenssegers/laravel-mongodb to have Eloquent queries for MongoDB, is there a way to use this caching with that library?

My following the basic set up I get

`Call to a member function prepare() on null`

at

```
Illuminate\Database\Connection::Illuminate\Database\{closure}
vendor/laravel/framework/src/Illuminate/Database/Connection.php:331
...

$statement = $this->prepared(
                $this->getPdoForSelect($useReadPdo)->prepare($query)
)
            
```

**Comment by rennokki** [comment]
MongoDB package is not supported. And even if it would get support, the caching is done on a query-basis, meaning that the query string acts like a caching key, and MongoDB does not support `->toSql()`. Any discussion on this issue is highly appreciated.
