### ISSUE TITLE
Relationship belongsToMany doesn't work

### ISSUE THREAD

**Issue by muratcakmakjengal** [renoki-co/laravel-eloquent-query-cache#68]
Hello, I encountered a problem, Can you help ?

![image](https://user-images.githubusercontent.com/84508273/119658158-7fb45180-be35-11eb-81ab-cb1368b3df1a.png)

![image](https://user-images.githubusercontent.com/84508273/119658410-c904a100-be35-11eb-8669-1811ea9e86e2.png)

![image](https://user-images.githubusercontent.com/84508273/119658371-bbe7b200-be35-11eb-8ea9-100ecbfb31b9.png)

How I can fixed ?
There is my fault ?

**Comment by rennokki** [comment]
Caching for many-to-many doesn't work yet.

**Comment by muratcakmakjengal** [comment]
Ty for answer. We are waiting new version 👍 and there is one more problem. I wrote you other issue

**Comment by DeepDiver1975** [comment]
same for belongsTo I assume?

```
[2021-06-30 14:10:11] testing.ERROR: Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::cacheFor() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\BelongsTo::cacheFor() at ..../vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)

**Comment by rennokki** [comment]
@DeepDiver1975 I have spent a lot of time finding out what the issue was. None found. The `BelongsTo`, like any other relationship that extends the `Relation` class, proxies the calls to the query builder underneath. This means that it should work if all models got set properly.

**Comment by muratcakmakjengal** [comment]
Hello, Caching for many-to-many will it come ? ⅎⅎ

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I have spent a lot of time finding out what the issue was. None found. The `BelongsTo`, like any other relationship that extends the `Relation` class, proxies the calls to the query builder underneath. This means that it should work if all models got set properly.

@rennokki THX a lot for looking into this - I finally got this working (I honestly don't remember what fixed this :see_no_evil: )
Sending some virtual :beers: .... THX

**Comment by rennokki** [comment]
@muratcakmakjengal The latest version contains it. https://github.com/renoki-co/laravel-eloquent-query-cache/pull/78, issue: https://github.com/renoki-co/laravel-eloquent-query-cache/issues/53

**Comment by rennokki** [comment]
@DeepDiver1975 I can hear the cling sounds 🍻 Got more time for open source from now on.

**Comment by rennokki** [comment]
By the way, documentation moved to Gitbook, and the documentation for Many-to-many flush is here: https://leqc.renoki.org/cache-tags/cache-invalidation/many-to-many-automatic-cache-invalidation
