### ISSUE TITLE
Handle cache saving depending on environment

### ISSUE THREAD

**Issue by ajmeireles** [renoki-co/laravel-eloquent-query-cache#73]
Hi!

First of all, this package has saved my project! Haha.

I want know if we have some method to control the cache saving based on environment. For i.e:
- I dont want save the cache if I'm on development environment.

I solved this problem like this:
![image](https://user-images.githubusercontent.com/60591772/125360406-2f8c4280-e342-11eb-8053-d9631d8bf014.png)

... but the cache file still generated (but not used in next query)!

It would be interesting if we could do:
`$query->dontCache(true/false);`

So we could use the conditional of the environment variable

**Comment by rennokki** [comment]
Besides the feature that'll be merged ASAP, please don't use the `env()` function within the code. Declare the `CACHE_ANNOUNCEMENT` within a `config/*.php` file and call the `config('path.to.value')` function. Read the warning from this section: https://laravel.com/docs/8.x/configuration#configuration-caching

**Comment by ajmeireles** [comment]
> Besides the feature that'll be merged ASAP, please don't use the `env()` function within the code. Declare the `CACHE_ANNOUNCEMENT` within a `config/*.php` file and call the `config('path.to.value')` function. Read the warning from this section: https://laravel.com/docs/8.x/configuration#configuration-caching

Thank you! Is it necessary to update README.md over PR? I could even create a documentation with readthedocs + sphinx if you want, like that: https://respect-validation.readthedocs.io/en/latest/
