### ISSUE TITLE
Cache won't flush if set cache for

### ISSUE THREAD

**Issue by binhluong2012** [renoki-co/laravel-eloquent-query-cache#76]
When set  $flushCacheOnUpdate, flush won't work.
Use User::flushQueryCache() to force flush still not working.
Please check

**Comment by rennokki** [comment]
Please describe a bit what caching driver you used and perhaps share a bit of your code to find out what's not working.

**Comment by binhluong2012** [comment]
i'm using 
CACHE_DRIVER=file

when set 
public $cacheFor = 60 * 60 * 24 * 7;

$flushCacheOnUpdate and <Model>::flushQueryCache() not working

Example 
this is working fine
![image](https://user-images.githubusercontent.com/29191103/126019827-3fa83ba0-92b6-4403-b62d-fea8f691fc8e.png)
this not working
![image](https://user-images.githubusercontent.com/29191103/126019866-9a7b6fb7-3eea-49eb-a3df-181c35bb5f9e.png)

**Comment by rennokki** [comment]
The file driver does not support tags. It's a Laravel limitation.
