### ISSUE TITLE
Concrete Explanation about Cache Tags

### ISSUE THREAD

**Issue by ajmeireles** [renoki-co/laravel-eloquent-query-cache#83]
First of all I would like to say that this package solves a very big problem for me.

Now I would like to know about cacheTags. I'll explain in detail, I don't know if I didn't understand or if it's not working properly.

I have the `getThroughId` method, and in it I set the cache tag to: _'announcement:id_1'_, **for example**. However when I parse the cache via Redis-cli, I see that this "tag" is empty, and the cache has really gone somewhere else, something like:
"laravel_database_laravel_cache:d8480f04bdab8f0a2bfe7798e478abff705048d8:leqc:2ae5775e226f5a09747f7d249952285ce8b9cb4c68f35a43000a2f6d291ee053"

Images:

The tag that I want
![image](https://user-images.githubusercontent.com/60591772/128197843-b7b94427-16cb-4990-80a6-2fb8ead9ae13.png)

The value on it:
![image](https://user-images.githubusercontent.com/60591772/128197936-dfaaa241-798e-4edc-8e98-3e9c2438bdc4.png)
***EMPTY!***

But analyzing another one with a bigger name:
![image](https://user-images.githubusercontent.com/60591772/128198517-bdc1f8b6-d031-44cb-920f-0b0b6d06016b.png)
**The contet is there!**

So I would like to know **why when I call cacheTags it doesn't insert the content into it, but into another index?**

**Comment by rennokki** [comment]
[Cache Tags are used to mark content](https://leqc.renoki.org/cache-tags/cache-tags), just so you can later invalidate specific queries.

The keys differ on a query-to-query basis : [_The package has the ability to track the SQL used and use it as a key in the cache storage, making the caching query-by-query a breeze, independent of your ORM usage._](https://leqc.renoki.org/getting-started/showcase)

The SQL queries are being hashed by default. You can disable the hashing by [setting a `public $cacheUsePlainKey = true;`](https://github.com/renoki-co/laravel-eloquent-query-cache/blob/3.0.0/src/Traits/QueryCacheable.php#L106-L108)
