### ISSUE TITLE
Error? Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::cacheTags() 

### ISSUE THREAD

**Issue by generalov-viktar** [renoki-co/laravel-eloquent-query-cache#84]
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::cacheTags() 

My code:

```
return PostUsersComment::with([
            'user' => function ($query) use($post) {
                return $query
                    ->cacheTags(["post:{$post->id}:comments:user"])
                    ->select(['id', 'name']);
            }
        ])
            ->where('post_id', 65)
            ->latest()
            ->paginate(10);
```
            
Why?

**Comment by ajmeireles** [comment]
Hey, @generalov-viktar !

Are you included the `QueryCacheable` trait in specific model who you want to the cache?

**Comment by generalov-viktar** [comment]
> Hey, @generalov-viktar !
> 
> Are you included the `QueryCacheable` trait in specific model who you want to the cache?

Hi! Yes

```
use Rennokki\QueryCache\Traits\QueryCacheable;
...
use QueryCacheable;
```

**Comment by rennokki** [comment]
When calling a relationship, the model used will be the relation's model, not the parent model. [Make sure you have set up the models properly](https://leqc.renoki.org/cache-tags/relationships-caching#relationship-classes)
