### ISSUE TITLE
setting for cacheFor as function AND varibale

### ISSUE THREAD

**Issue by rognales** [renoki-co/laravel-eloquent-query-cache#89]
is it possible to set the time to cache in form of function and variable

````php
    /**
     * Specify the amount of time to cache queries.
     * Do not specify or set it to null to disable caching.
     *
     * @var int|\DateTime
     */
    public $cacheFor = 3600;

    /**
     * Specify the amount of time to cache queries.
     * Set it to null to disable caching.
     *
     * @return mixed
     */
    public function cacheFor()
    {
        if (request()->user()->hasRole('admin')) {
            return null;
        }

        return 1337;
    }

````

that way, we can conditionally handle the cache which helps with 
- settings across environments
- some User (admins) always bypass the cache

**Comment by rennokki** [comment]
This might be useful:

```php
Post::when(! request()->user()->hasRole('admin'), function ($query) {
    $query->cacheFor(1337);
})->get();
```

**Comment by rennokki** [comment]
`cacheFor()` does not exist directly in the model, it is a subsidiary of the eloquent query, which is another thing. I think this conditional caching might be useful 🤔

**Comment by rennokki** [comment]
@rognales Tagged `3.1.0`, now supports methods to be defined within the model and conditionally define values within them: https://leqc.renoki.org/cache-tags/query-caching#defining-values-dynamically

**Comment by rognales** [comment]
That's a wish came true! Thanks @rennokki for the prompt response.
