### ISSUE TITLE
Trying to access array offset on value of type null - Cache::partialMock()

### ISSUE THREAD

**Issue by mrbenosborne** [renoki-co/laravel-eloquent-query-cache#95]
I have query caching enabled on a model but when I use:

```
Cache::partialMock();
```

in a test I get the below error:

ErrorException : Trying to access array offset on value of type null

/vendor/rennokki/laravel-eloquent-query-cache/src/Traits/QueryCacheModule.php:337

**Comment by rennokki** [comment]
Version?

**Comment by mrbenosborne** [comment]
v2.7.0

**Comment by rennokki** [comment]
I think you haven't use `partialMock` correctly: https://github.com/laravel/framework/issues/35870

**Comment by mrbenosborne** [comment]
> I think you haven't use `partialMock` correctly: https://github.com/laravel/framework/issues/35870

I think I am, there isn't much too it, ie. Call the partialMock() method?

Seems like people are still having issues on the thread you tagged?
