### ISSUE TITLE
On update, only flush the updated model from the cache - not all of cache

### ISSUE THREAD

**Issue by AlaaHam91** [renoki-co/laravel-eloquent-query-cache#97]
When we update some Model Instead of flushing the cache of this model, All the Models cache is flushed even though I have this parameter set to TRUE.

I call this trait in each model instead of writing them in every one.

<?php

namespace App\Traits;

use Rennokki\QueryCache\Traits\QueryCacheable;

trait  GlobalQueryCacheable

{
    use QueryCacheable,Cachable;

    protected function cacheForValue()
    {
        return env('CACHE_INTERVAL', 5 * 12 * 30 * 24 * 60 * 60);
    }

    protected function cacheDriverValue()
    {
        return env('CACHE_DRIVER', 'file');
    }

    protected static $flushCacheOnUpdate = true;
}

**Comment by AlaaHam91** [comment]
I need to flush all cache queries for the updated model only, not specific queries in that model,
since that the default base tag for each model is the class name.
@rennokki

**Comment by AlaaHam91** [comment]
Any update dear ?

**Comment by rennokki** [comment]
Sorry for these big delays. Usually, I'm doing open-source in my free time. It took me some time to investigate and didn't find anything resembling this bug. Do you have a specific example I can test out?
